substitutions:
    suuid: 0000a0a0-3c17-d293-8e48-14fe2e4da212
    cuuid: 0000a001-0000-1000-8000-00805f9b34fb
    device_mac: XX:XX:XX:XX:XX:XX

esp32:
    board: esp32-c6-devkitc-1
    flash_size: 4MB
    framework:
        type: esp-idf
        version: 5.3.1
        platform_version: 6.9.0

esphome:
    name: "3pro"

logger:

wifi:
    ssid: !secret wifi_ssid
    password: !secret wifi_password

api:

ota:
    - platform: esphome

esp32_ble_tracker:

ble_client:
    id: black_shark_3pro
    mac_address: ${device_mac}
    auto_connect: true

light:
    - platform: binary
      name: "黑鲨散热器"
      id: black_shark_3pro_light
      output: light_output

output:
    - platform: template
      id: light_output
      type: binary
      write_action:
          - ble_client.ble_write:
                id: black_shark_3pro
                service_uuid: ${suuid}
                characteristic_uuid: ${cuuid}
                value: !lambda |-
                    uint8_t value = 0x00;
                    if (state == 1) {
                        value = 0x01;  // 开启
                    } else {
                        value = 0x00;  // 关闭
                    }
                    return std::vector<uint8_t>{0x85, 0x01, 0x08, 0x00, value};
